---
# The level of loggin output.
# Accepted options are:
#   - debug
#   - info
#   - warn
#   - error
logLevel: info

# The webserver configuration
server:
  # The port where the server will listen on
  port: 8080
  # (Optional) Configure SSL
  ssl:
    # If the SSL is enabled
    enabled: false
    # The path to the certificate file
    cert: ""
    # The path to the key file
    key: ""

# Configure where the data will be stored
storage:
  # The backend to use for storage.
  #
  # Accepted options are:
  #   - file
  #   - valkey
  type: "file"
  # If the storage should be readonly.
  # If set to false, will check if the backend is writable on startup
  readonly: true
  # Path to an optional hosts.yaml file to seed known hosts from on startup.
  seeded-hosts: ""
  # The configuration for the file backend
  file:
    # The path to the hosts file. Will be created if it does not exist
    path: "hosts.yaml"
  # The configuration for the valkey (redis) backend
  valkey:
    # The address of the valkey server
    addresses:
      - "localhost:6379"
    # The username for the valkey server
    username: ""
    # The password for the valkey server
    password: ""
    # The database to use
    db: 0
    # Enable if using TLS
    tls: false
    # Enable if using sentinel
    sentinel: false
    # The name of the sentinel master
    master: ""
