---
name: "Generate go test cover report"

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  generate-reports:
    uses: heathcliff26/ci/.github/workflows/golang-testcover-report.yaml@main
    secrets: inherit
    permissions: {}
    with:
      coveralls: true
      script: |
        sudo sysctl -w net.ipv4.ping_group_range="0 2147483647"
        make coverprofile
